// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http_session.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpSession struct {
	Request              *HttpRequest  `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	Response             *HttpResponse `protobuf:"bytes,2,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HttpSession) Reset()         { *m = HttpSession{} }
func (m *HttpSession) String() string { return proto.CompactTextString(m) }
func (*HttpSession) ProtoMessage()    {}
func (*HttpSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_b131466a29edf02c, []int{0}
}

func (m *HttpSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpSession.Unmarshal(m, b)
}
func (m *HttpSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpSession.Marshal(b, m, deterministic)
}
func (m *HttpSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpSession.Merge(m, src)
}
func (m *HttpSession) XXX_Size() int {
	return xxx_messageInfo_HttpSession.Size(m)
}
func (m *HttpSession) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpSession.DiscardUnknown(m)
}

var xxx_messageInfo_HttpSession proto.InternalMessageInfo

func (m *HttpSession) GetRequest() *HttpRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *HttpSession) GetResponse() *HttpResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type HttpHeader struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpHeader) Reset()         { *m = HttpHeader{} }
func (m *HttpHeader) String() string { return proto.CompactTextString(m) }
func (*HttpHeader) ProtoMessage()    {}
func (*HttpHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b131466a29edf02c, []int{1}
}

func (m *HttpHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpHeader.Unmarshal(m, b)
}
func (m *HttpHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpHeader.Marshal(b, m, deterministic)
}
func (m *HttpHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpHeader.Merge(m, src)
}
func (m *HttpHeader) XXX_Size() int {
	return xxx_messageInfo_HttpHeader.Size(m)
}
func (m *HttpHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpHeader.DiscardUnknown(m)
}

var xxx_messageInfo_HttpHeader proto.InternalMessageInfo

func (m *HttpHeader) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HttpHeader) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HttpRequest struct {
	Host                 string        `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 uint32        `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Verb                 string        `protobuf:"bytes,3,opt,name=Verb,proto3" json:"Verb,omitempty"`
	Uri                  string        `protobuf:"bytes,4,opt,name=Uri,proto3" json:"Uri,omitempty"`
	HttpVersion          string        `protobuf:"bytes,5,opt,name=HttpVersion,proto3" json:"HttpVersion,omitempty"`
	Headers              []*HttpHeader `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte        `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HttpRequest) Reset()         { *m = HttpRequest{} }
func (m *HttpRequest) String() string { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()    {}
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b131466a29edf02c, []int{2}
}

func (m *HttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequest.Unmarshal(m, b)
}
func (m *HttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequest.Marshal(b, m, deterministic)
}
func (m *HttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequest.Merge(m, src)
}
func (m *HttpRequest) XXX_Size() int {
	return xxx_messageInfo_HttpRequest.Size(m)
}
func (m *HttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequest proto.InternalMessageInfo

func (m *HttpRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HttpRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *HttpRequest) GetVerb() string {
	if m != nil {
		return m.Verb
	}
	return ""
}

func (m *HttpRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HttpRequest) GetHttpVersion() string {
	if m != nil {
		return m.HttpVersion
	}
	return ""
}

func (m *HttpRequest) GetHeaders() []*HttpHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HttpResponse struct {
	Host                 string        `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 uint32        `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Version              string        `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Code                 int32         `protobuf:"varint,4,opt,name=Code,proto3" json:"Code,omitempty"`
	Headers              []*HttpHeader `protobuf:"bytes,5,rep,name=Headers,proto3" json:"Headers,omitempty"`
	Body                 []byte        `protobuf:"bytes,6,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HttpResponse) Reset()         { *m = HttpResponse{} }
func (m *HttpResponse) String() string { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()    {}
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b131466a29edf02c, []int{3}
}

func (m *HttpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponse.Unmarshal(m, b)
}
func (m *HttpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponse.Marshal(b, m, deterministic)
}
func (m *HttpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponse.Merge(m, src)
}
func (m *HttpResponse) XXX_Size() int {
	return xxx_messageInfo_HttpResponse.Size(m)
}
func (m *HttpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponse proto.InternalMessageInfo

func (m *HttpResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HttpResponse) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *HttpResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *HttpResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HttpResponse) GetHeaders() []*HttpHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpSession)(nil), "types.HttpSession")
	proto.RegisterType((*HttpHeader)(nil), "types.HttpHeader")
	proto.RegisterType((*HttpRequest)(nil), "types.HttpRequest")
	proto.RegisterType((*HttpResponse)(nil), "types.HttpResponse")
}

func init() { proto.RegisterFile("http_session.proto", fileDescriptor_b131466a29edf02c) }

var fileDescriptor_b131466a29edf02c = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0xe9, 0xdf, 0x69, 0xfb, 0xf7, 0x76, 0x04, 0x8d, 0x2e, 0xb2, 0x2c, 0x5d, 0x15, 0x94,
	0x0a, 0xa3, 0x4f, 0xa0, 0x9b, 0x82, 0x1b, 0x89, 0x4c, 0xb7, 0x32, 0xa5, 0x17, 0xa6, 0x30, 0x4c,
	0x6a, 0x92, 0x59, 0xf4, 0x81, 0x7c, 0x0d, 0x9f, 0x4d, 0xee, 0x4d, 0xab, 0x75, 0x21, 0xb8, 0x3b,
	0xb9, 0xf7, 0x34, 0xe7, 0x3b, 0xa1, 0x20, 0xf6, 0xce, 0x0d, 0xaf, 0x16, 0xad, 0xed, 0xf5, 0xb1,
	0x1a, 0x8c, 0x76, 0x5a, 0x44, 0x6e, 0x1c, 0xd0, 0x16, 0x07, 0xc8, 0x6a, 0xe7, 0x86, 0x17, 0xbf,
	0x13, 0x37, 0x90, 0x28, 0x7c, 0x3b, 0xa1, 0x75, 0x32, 0xc8, 0x83, 0x32, 0xdb, 0x88, 0x8a, 0x7d,
	0x15, 0x99, 0xa6, 0x8d, 0x9a, 0x2d, 0xe2, 0x16, 0xfe, 0x2b, 0xb4, 0x83, 0x3e, 0x5a, 0x94, 0xff,
	0xd8, 0x7e, 0xf9, 0xc3, 0xee, 0x57, 0xea, 0xcb, 0x54, 0xdc, 0x03, 0xd0, 0xa6, 0xc6, 0x5d, 0x87,
	0x46, 0x9c, 0x43, 0xf8, 0x84, 0x23, 0x07, 0xa5, 0x8a, 0xa4, 0xb8, 0x82, 0xa8, 0xd9, 0x1d, 0x4e,
	0xfe, 0xb6, 0x54, 0xf9, 0x43, 0xf1, 0x11, 0x78, 0xc8, 0x39, 0x56, 0xc0, 0xaa, 0xd6, 0x13, 0x61,
	0xaa, 0x58, 0xd3, 0xec, 0x59, 0x1b, 0xc7, 0x1f, 0x9e, 0x29, 0xd6, 0x34, 0x6b, 0xd0, 0xb4, 0x32,
	0xf4, 0x3e, 0xd2, 0x94, 0xb9, 0x35, 0xbd, 0x5c, 0xf9, 0xcc, 0xad, 0xe9, 0x45, 0xee, 0x2f, 0x6f,
	0xd0, 0xd0, 0x0b, 0xc8, 0x88, 0x37, 0xcb, 0x91, 0xb8, 0x86, 0x64, 0xcf, 0xc4, 0x56, 0xc6, 0x79,
	0x58, 0x66, 0x9b, 0x8b, 0x45, 0x4b, 0xdf, 0x45, 0xcd, 0x0e, 0x0a, 0x6d, 0x75, 0x37, 0xca, 0x24,
	0x0f, 0xca, 0xb5, 0x62, 0x5d, 0xbc, 0x07, 0xb0, 0x5e, 0xbe, 0xc8, 0x9f, 0x1b, 0x48, 0x48, 0x66,
	0x2e, 0x5f, 0x62, 0x3e, 0x92, 0xfb, 0x51, 0x77, 0xc8, 0x45, 0x22, 0xc5, 0x9a, 0x38, 0xeb, 0x89,
	0x33, 0xfa, 0x95, 0xb3, 0xfe, 0xe6, 0x7c, 0x20, 0xce, 0xd8, 0x73, 0x92, 0x6e, 0x63, 0xfe, 0x35,
	0xee, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x15, 0xe8, 0x9f, 0x06, 0x30, 0x02, 0x00, 0x00,
}
