// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcp_session.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TcpSession struct {
	SrcEndpoint          *Endpoint `protobuf:"bytes,1,opt,name=SrcEndpoint,proto3" json:"SrcEndpoint,omitempty"`
	SrcData              []byte    `protobuf:"bytes,2,opt,name=SrcData,proto3" json:"SrcData,omitempty"`
	DstEndpoint          *Endpoint `protobuf:"bytes,3,opt,name=DstEndpoint,proto3" json:"DstEndpoint,omitempty"`
	DstData              []byte    `protobuf:"bytes,4,opt,name=DstData,proto3" json:"DstData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TcpSession) Reset()         { *m = TcpSession{} }
func (m *TcpSession) String() string { return proto.CompactTextString(m) }
func (*TcpSession) ProtoMessage()    {}
func (*TcpSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1e2d90319d9258, []int{0}
}

func (m *TcpSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpSession.Unmarshal(m, b)
}
func (m *TcpSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpSession.Marshal(b, m, deterministic)
}
func (m *TcpSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpSession.Merge(m, src)
}
func (m *TcpSession) XXX_Size() int {
	return xxx_messageInfo_TcpSession.Size(m)
}
func (m *TcpSession) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpSession.DiscardUnknown(m)
}

var xxx_messageInfo_TcpSession proto.InternalMessageInfo

func (m *TcpSession) GetSrcEndpoint() *Endpoint {
	if m != nil {
		return m.SrcEndpoint
	}
	return nil
}

func (m *TcpSession) GetSrcData() []byte {
	if m != nil {
		return m.SrcData
	}
	return nil
}

func (m *TcpSession) GetDstEndpoint() *Endpoint {
	if m != nil {
		return m.DstEndpoint
	}
	return nil
}

func (m *TcpSession) GetDstData() []byte {
	if m != nil {
		return m.DstData
	}
	return nil
}

type Endpoint struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1e2d90319d9258, []int{1}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Endpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*TcpSession)(nil), "types.TcpSession")
	proto.RegisterType((*Endpoint)(nil), "types.Endpoint")
}

func init() { proto.RegisterFile("tcp_session.proto", fileDescriptor_0b1e2d90319d9258) }

var fileDescriptor_0b1e2d90319d9258 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x49, 0x2e, 0x88,
	0x2f, 0x4e, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d,
	0xa9, 0x2c, 0x48, 0x2d, 0x56, 0x5a, 0xc6, 0xc8, 0xc5, 0x15, 0x92, 0x5c, 0x10, 0x0c, 0x91, 0x13,
	0x32, 0xe4, 0xe2, 0x0e, 0x2e, 0x4a, 0x76, 0xcd, 0x4b, 0x29, 0xc8, 0xcf, 0xcc, 0x2b, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd7, 0x03, 0xab, 0xd5, 0x83, 0x09, 0x07, 0x21, 0xab, 0x11,
	0x92, 0xe0, 0x62, 0x0f, 0x2e, 0x4a, 0x76, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0,
	0x09, 0x82, 0x71, 0x41, 0x86, 0xb9, 0x14, 0x97, 0xc0, 0x0d, 0x63, 0xc6, 0x61, 0x18, 0x92, 0x1a,
	0x90, 0x61, 0x2e, 0xc5, 0x25, 0x60, 0xc3, 0x58, 0x20, 0x86, 0x41, 0xb9, 0x4a, 0x7a, 0x5c, 0x1c,
	0x70, 0x55, 0x7c, 0x5c, 0x4c, 0x9e, 0x05, 0x60, 0xc7, 0x71, 0x06, 0x31, 0x79, 0x16, 0x08, 0x09,
	0x71, 0xb1, 0x04, 0xe4, 0x17, 0x95, 0x80, 0xed, 0x67, 0x0d, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0xde,
	0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x62, 0x91, 0xf6, 0x57, 0xfb, 0x00, 0x00, 0x00,
}
